var b=Object.defineProperty;var S=(n,t,r)=>t in n?b(n,t,{enumerable:!0,configurable:!0,writable:!0,value:r}):n[t]=r;var h=(n,t,r)=>S(n,typeof t!="symbol"?t+"":t,r);(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))f(o);new MutationObserver(o=>{for(const a of o)if(a.type==="childList")for(const _ of a.addedNodes)_.tagName==="LINK"&&_.rel==="modulepreload"&&f(_)}).observe(document,{childList:!0,subtree:!0});function r(o){const a={};return o.integrity&&(a.integrity=o.integrity),o.referrerPolicy&&(a.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?a.credentials="include":o.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function f(o){if(o.ep)return;o.ep=!0;const a=r(o);fetch(o.href,a)}})();let i;function U(n){return i=n.getContext("webgl2")}function P(n,t){const r=i.createShader(n);if(!r)return null;if(i.shaderSource(r,t),i.compileShader(r),!i.getShaderParameter(r,i.COMPILE_STATUS)){const o=i.getShaderInfoLog(r);return console.error(o),i.deleteShader(r),null}return r}function L(n){const t=i.createProgram(),r=[];for(const o in n){const a=n[o],_=P(parseInt(o),a);if(!_){for(const v of r)i.deleteShader(v);return null}r.push(_)}for(const o of r)i.attachShader(t,o);i.linkProgram(t);for(const o of r)i.detachShader(t,o),i.deleteShader(o);if(!i.getProgramParameter(t,i.LINK_STATUS)){const o=i.getProgramInfoLog(t);return console.error(o),i.deleteProgram(t),null}return t}document.body.style.margin="0";document.body.style.height="100vh";document.body.style.overflow="hidden";const l=document.createElement("canvas");l.width=document.body.clientWidth;l.height=document.body.clientHeight;document.body.append(l);addEventListener("resize",function(){l.width=document.body.clientWidth,l.height=document.body.clientHeight});const e=U(l),g=L({[e.VERTEX_SHADER]:`#version 300 es
    layout(location = 0) in vec2 i_position;
    layout(location = 1) in vec2 i_tex_coord;
    out vec2 v_tex_coord;
    uniform float u_scale_x;
    uniform float u_scale_y;

    void main() {
        gl_Position = vec4(i_position * vec2(u_scale_x, u_scale_y), 0.0, 1.0);
        v_tex_coord = i_tex_coord;
    }
`,[e.FRAGMENT_SHADER]:`#version 300 es
    precision highp float;
    in vec2 v_tex_coord;
    out vec4 o_frag_color;
    uniform sampler2D u_texture;

    void main() {
        o_frag_color = texture(u_texture, v_tex_coord);
    }
`}),D=e.getUniformLocation(g,"u_scale_x"),N=e.getUniformLocation(g,"u_scale_y"),I=[-1,1,0,0,-1,-1,0,1,1,-1,1,1,1,1,1,0],x=[0,1,2,0,2,3],F=x.length,y=e.createVertexArray();e.bindVertexArray(y);const B=e.createBuffer();e.bindBuffer(e.ARRAY_BUFFER,B);e.bufferData(e.ARRAY_BUFFER,new Float32Array(I),e.STATIC_DRAW);e.enableVertexAttribArray(0);e.vertexAttribPointer(0,2,e.FLOAT,!1,16,0);e.enableVertexAttribArray(1);e.vertexAttribPointer(1,2,e.FLOAT,!1,16,8);const w=e.createBuffer();e.bindBuffer(e.ELEMENT_ARRAY_BUFFER,w);e.bufferData(e.ELEMENT_ARRAY_BUFFER,new Uint32Array(x),e.STATIC_DRAW);const d=512,u=512,T=3,G=d*u*T,s=new Uint8Array(G);for(let n=0;n<u;++n)for(let t=0;t<u;++t){const r=R(t,n,d)*T;s[r]=255,s[r+1]=255,s[r+2]=255}const M=e.createTexture();e.bindTexture(e.TEXTURE_2D,M);e.pixelStorei(e.UNPACK_ALIGNMENT,1);e.texImage2D(e.TEXTURE_2D,0,e.RGB,d,u,0,e.RGB,e.UNSIGNED_BYTE,s);e.texParameteri(e.TEXTURE_2D,e.TEXTURE_MIN_FILTER,e.NEAREST);e.texParameteri(e.TEXTURE_2D,e.TEXTURE_MAG_FILTER,e.NEAREST);e.texParameteri(e.TEXTURE_2D,e.TEXTURE_WRAP_S,e.CLAMP_TO_EDGE);e.texParameteri(e.TEXTURE_2D,e.TEXTURE_WRAP_T,e.CLAMP_TO_EDGE);function A(n,t){return Math.floor(Math.random()*(t-n)+n)}function R(n,t,r){return t*r+n}function m(n,t){return(n+t)%t}const E=[[0,1],[1,0],[0,-1],[-1,0]];class O{constructor(){h(this,"x");h(this,"y");h(this,"dir")}}const c=new O;c.x=A(0,d);c.y=A(0,u);c.dir=0;function X(){const n=Math.min(l.width,l.height);for(let t=0;t<100;t+=1){const r=R(c.x,c.y,d)*T;s[r]?(c.dir=m(c.dir-1,E.length),s[r]=0,s[r+1]=0,s[r+2]=0):(c.dir=m(c.dir+1,E.length),s[r]=255,s[r+1]=255,s[r+2]=255);const o=E[c.dir];c.x=m(c.x+o[0],d),c.y=m(c.y+o[1],u)}e.texImage2D(e.TEXTURE_2D,0,e.RGB,d,u,0,e.RGB,e.UNSIGNED_BYTE,s),e.viewport(0,0,l.width,l.height),e.clearColor(0,0,0,1),e.clear(e.COLOR_BUFFER_BIT),e.useProgram(g),e.uniform1f(D,n/l.width),e.uniform1f(N,n/l.height),e.bindVertexArray(y),e.drawElements(e.TRIANGLES,F,e.UNSIGNED_INT,0)}function p(){X(),requestAnimationFrame(p)}p();
